#!/bin/bash -eux
URL=${PWD##*/}
db_container_name=`echo ${URL}_db_1 | sed "s/\.//g" | sed "s/-//g"`; \

docker exec $db_container_name mysqldump --all-databases --events -uadmin -p$MYSQL_ROOT_PASSWORD -h db > /dump/dump.sql
