#!/bin/bash -eux

mkdir -p ./data/config

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > .env

cat > ./data/config/config.php <<EOF
<?php
\$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => '${url}',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'https://${url}',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => '${MYSQL_ROOT_PASSWORD}',
  'theme' => '',
  'maintenance' => false,
  'mail_domain' => 'indie.host',
  'mail_from_address' => 'noreply.${url}',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.indie.host',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply.${url}',
  'mail_smtppassword' => '${email_password}@indie.host',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
EOF
